import { parseAbi } from "viem"

export const blockchainGameAbi = parseAbi([
  "function OPERATOR_ROLE() view returns (bytes32)",
  "function TREASURER_ROLE() view returns (bytes32)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function minBetAmount() view returns (uint256)",
  "function accruedFees() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function getRoundIds() view returns (uint256[])",
  "function getRound(uint256 roundId) view returns ((uint256 id, string title, string metadataURI, uint8 status, uint8 winningSide, uint64 createdAt, uint64 openedAt, uint64 closedAt, uint64 settledAt, uint64 canceledAt, uint256 totalPool, uint256 feeAmount, uint256 netPayoutPool, uint256 sideATotal, uint256 sideBTotal, uint256 bettorCount) roundView)",
  "function getPlayerBet(uint256 roundId, address player) view returns (uint256 amount, uint8 side, bool placed, bool claimed)",
  "function getGlobalStats() view returns ((uint256 activeRounds, uint256 totalRoundsCreated, uint256 totalRoundsTracked, uint256 activeDraftRounds, uint256 activeOpenRounds, uint256 activeClosedRounds, uint256 totalSettledRounds, uint256 totalCanceledRounds, uint256 totalVolumeStaked, uint256 accruedFees) stats)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function placeBet(uint256 roundId, uint8 side, uint256 amount)",
  "function claimPayout(uint256 roundId) returns (uint256 payoutAmount)",
  "function claimRefund(uint256 roundId) returns (uint256 refundAmount)",
  "function createRound(string title, string metadataURI) returns (uint256 roundId)",
  "function updateRound(uint256 roundId, string title, string metadataURI)",
  "function deleteRound(uint256 roundId)",
  "function openRound(uint256 roundId)",
  "function closeRound(uint256 roundId)",
  "function settleRound(uint256 roundId)",
  "function cancelRound(uint256 roundId)",
  "function mint(address to, uint256 amount)",
  "function setMinBetAmount(uint256 newMinBetAmount)",
  "function withdrawFees(address recipient, uint256 amount)",
  "event RoundCreated(uint256 indexed roundId, string title, string metadataURI)",
  "event RoundUpdated(uint256 indexed roundId, string title, string metadataURI)",
  "event RoundDeleted(uint256 indexed roundId)",
  "event RoundOpened(uint256 indexed roundId, uint64 openedAt)",
  "event BetPlaced(uint256 indexed roundId, address indexed player, uint8 side, uint256 amount)",
  "event RoundClosed(uint256 indexed roundId, uint64 closedAt)",
  "event RoundSettled(uint256 indexed roundId, uint8 winningSide, uint256 totalPool, uint256 feeAmount, uint256 netPayoutPool, uint256 randomness)",
  "event RoundCanceled(uint256 indexed roundId, uint64 canceledAt)",
  "event PayoutClaimed(uint256 indexed roundId, address indexed player, uint256 payoutAmount)",
  "event RefundClaimed(uint256 indexed roundId, address indexed player, uint256 refundAmount)",
  "event FeesWithdrawn(address indexed caller, address indexed recipient, uint256 amount)",
  "event TokensMinted(address indexed to, uint256 amount)",
  "event MinBetAmountUpdated(uint256 previousMinBetAmount, uint256 newMinBetAmount)",
  "error ZeroAddress()",
  "error ZeroAmount()",
  "error RoundNotFound(uint256 roundId)",
  "error InvalidRoundStatus(uint256 roundId, uint8 expectedStatus, uint8 currentStatus)",
  "error RoundAlreadyFinalized(uint256 roundId, uint8 currentStatus)",
  "error RoundHasBettors(uint256 roundId)",
  "error RoundHasNoBets(uint256 roundId)",
  "error BetAlreadyPlaced(uint256 roundId, address player)",
  "error BetBelowMinimum(uint256 amount, uint256 minBetAmount)",
  "error BetNotPlaced(uint256 roundId, address player)",
  "error AlreadyClaimed(uint256 roundId, address player)",
  "error NotWinningSide(uint256 roundId, address player)",
  "error InsufficientFeeBalance(uint256 requested, uint256 available)",
  "error InvalidPagination()",
])
